name: pr-check

on:
  pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: cargo check --verbose

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
